POST http://localhost:5000/api/v1/hands/compare
Content-Type: application/json

{
  "hands": [
    [
      "DJ",
      "D3",
      "C4",
      "S6",
      "C7"
    ],
    [
      "H5",
      "H7",
      "SK",
      "DK",
      "CJ"
    ],
    [
      "CA",
      "HJ",
      "ST",
      "S8",
      "SA"
    ]
  ]
}